language: r
r:
  - release
cache: packages
sudo: false

warnings_are_errors: false

r_packages:
  - covr
  - httr
  - jsonlite
  - curl
  - testthat

r_github_packages:
  - r-lib/covr

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_failure: paul.spende@gmail.com
