language: r
r:
  - release
cache: packages
sudo: false

warnings_are_errors: false

r_packages:
  - covr
  - httr
  - jsonlite
  - curl
  - testthat

after_success:

  - Rscript \
    --default-packages='httr,curl,testthat,jsonlite' \
    -e 'library(covr); covr::codecov(token="1a2512eb-7044-4d30-9496-787465c38e37")'

notifications:
  email:
    on_failure: paul.spende@gmail.com
